version: "3.9"

services:
  app:
    container_name: golek_notifications_service_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: on-failure
    volumes:
      - app_vol:/app
      - ./firebaseKey.json:/root/firebaseKey.json
    networks:
      default:
        ipv4_address: 172.53.1.13

  db:
    image: mariadb:10.4
    container_name: golek_notifications_service_db
    environment:
      MYSQL_ROOT_HOST: "${DB_HOST}"
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_HOST}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - notif_db_vol:/var/lib/mysql
    #      - ./containers/mariadb/config:/etc/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      default:
        ipv4_address: "${DB_HOST}"
volumes:
  notif_db_vol:
  app_vol:

networks:
  default:
    name: golek_network_br
    external: true
#    driver: bridge
